In [1]:
import logging

import anndata as ad
import numpy as np
import pandas as pd
import scanpy as sc

In [2]:
# Init file paths
file_path_training = '/Users/cheshic/dev/test_data/neurips-2021/multiome/multiome_atac_processed_training.h5ad'

# Load data
sc_raw_training = sc.read(file_path_training)

In [22]:
sc_raw_training.obs

,nCount_peaks,atac_fragments,reads_in_peaks_frac,blacklist_fraction,nucleosome_signal,cell_type,pseudotime_order_ATAC,batch
TAGTTGTCACCCTCAC-1-s1d1,4031.0,5400,0.746481,0.003473,0.642468,Naive CD20+ B,NaN,s1d1
CTATGGCCATAACGGG-1-s1d1,8636.0,19266,0.448251,0.003126,1.220679,CD14+ Mono,NaN,s1d1
CCGCACACAGGTTAAA-1-s1d1,4674.0,6177,0.756678,0.001284,0.692573,CD8+ T,NaN,s1d1
TCATTTGGTAATGGAA-1-s1d1,2803.0,4019,0.697437,0.000714,0.633838,CD8+ T,NaN,s1d1
ACCACATAGGTGTCCA-1-s1d1,1790.0,2568,0.697040,0.003352,0.727660,CD16+ Mono,NaN,s1d1
...,...,...,...,...,...,...,...,...
TAGTAAGCAACTAGGG-8-s3d6,7239.0,10580,0.684216,0.000553,0.866142,HSC,0.23367,s3d6
TGGTCCTTCGGCTAGC-8-s3d6,16056.0,22771,0.705107,0.000810,0.964006,CD4+ T activated,NaN,s3d6
CGCTTGCGTTGTTGGA-8-s3d6,8388.0,14137,0.593337,0.000358,1.215227,pDC,NaN,s3d6
ACCCTCCCAGCCAGTT-8-s3d6,1001.0,1381,0.724837,0.000000,0.714286,CD8+ T,NaN,s3d6
AGTGAACCATCCCGCT-8-s3d6,3183.0,4684,0.679547,0.001257,0.946565,CD4+ T activated,NaN,s3d6

In [23]:
sc_raw_training.var

                        feature_types
chr1-9776-10668                  ATAC
chr1-180726-181005               ATAC
chr1-181117-181803               ATAC
chr1-191133-192055               ATAC
chr1-267562-268456               ATAC
...                               ...
GL000219.1-90062-90937           ATAC
GL000219.1-99257-100160          ATAC
KI270726.1-27152-28034           ATAC
KI270713.1-21434-22336           ATAC
KI270713.1-29629-30491           ATAC

[116490 rows x 1 columns]

In [24]:
#Â convert to list of lists format
matrix = sc_raw_training.X.tocoo()
matrix.shape

(22463, 116490)

In [30]:
# Print different formats
for i,j,v in zip(matrix.row, matrix.col, matrix.data):
    #print((i,j,v))
    #print((sc_raw_training.obs.index[i], sc_raw_training.var.index[j], v))
    
    line = sc_raw_training.obs.index[i] + "\t" + sc_raw_training.var.index[j] + "\t" + str(v)
    #print(line)
    
    line = sc_raw_training.obs.index[i] + "\tatac_peak\t" + sc_raw_training.var.index[j]
    #print(line)
    
    line1 = str(i) + "\tcell_peak\t" + str(j)
    print(line1)
    break

34	cell_peak	0